######################## default configuration ####################
baseURL = "https://brasalille.github.io/"
title = "BRASA Lille"
# post pagination
paginate = "2"
# post excerpt
summaryLength = "30"
# google analytics
googleAnalytics = "" # example: UA-123-45, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
publishDir= 'docs'

[module]
[module.hugoVersion]
extended = true
min = "0.83.1"

[outputs]
home = ["HTML", "RSS", "WebAppManifest"]

[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

[markup]
[markup.goldmark.renderer]
unsafe= true

[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]

[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"